--1 )
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE l.CITY = 'Tokyo';

--2)
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE LENGTH(l.POSTAL_CODE) > 7;

--3)
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE STATE_PROVINCE IS NOT NULL;

--4)
SELECT l.LOCATION_ID, l.STREET_ADDRESS, l.POSTAL_CODE, l.CITY, l.STATE_PROVINCE
FROM SQLBOT.LOCATIONS l
WHERE l.COUNTRY_ID LIKE('IT');

--5)
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE  l.LOCATION_ID > 2000;

--6)
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE LOWER(l.COUNTRY_ID) LIKE('ca');

--7)
SELECT SUBSTR(COUNTRY_ID, 1, 2) 
FROM SQLBOT.LOCATIONS l;

--8)
SELECT l.STREET_ADDRESS || ', ' || l.CITY AS Street_And_City
FROM SQLBOT.LOCATIONS l;

--9)
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE l.CITY LIKE('%ut%');

--10)
SELECT SUBSTR(l.CITY, 1, 2) || '. ' || SUBSTR(l.STREET_ADDRESS, 1, 10) 
FROM SQLBOT.LOCATIONS l
WHERE l.POSTAL_CODE IS NOT NULL;

--11)V1
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE l.COUNTRY_ID IN ('JP', 'CN', 'SG', 'IN');

--11)V2
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE (LENGTH(l.POSTAL_CODE) = 6 OR LENGTH(l.POSTAL_CODE) = 4)
AND SUBSTR(POSTAL_CODE,-1,1) != 'K'; 


--11)V3
SELECT l.*
FROM SQLBOT.LOCATIONS l
WHERE l.COUNTRY_ID IN (
	SELECT c.COUNTRY_ID 
	FROM SQLBOT.COUNTRIES c
	WHERE c.REGION_ID = (
		SELECT r.REGION_ID
		FROM SQLBOT.REGIONS r 
		WHERE r.REGION_NAME = 'Asia'
	)
);


SELECT *
FROM SQLBOT.LOCATIONS;


SELECT *
FROM SQLBOT.REGIONS r;

SELECT *
FROM SQLBOT.COUNTRIES c;